language: node_js
node_js:
  - "8.9.1"
sudo: required
addons:
  chrome: stable
env:
  - NPM_SCRIPT=server-coveralls
  - NPM_SCRIPT=client-coveralls
install:
  - "npm run install:all"
script:
  - "npm run test:$NPM_SCRIPT"
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN